banditcpp/bandit

specs/run.spec.cpp
I was getting
~~~
specs/run.spec.cpp:14:21: error: C++11 requires lambda with omitted result
type to consist of a single return statement [-Werror,-Wlambda-extensions]
auto call_run = [&](){
^
1 error generated.
~~~
solved by declare the lambda return type
=> run.spec.cpp call_run lambda return type

bandit/assertion_frameworks/matchers/MatcherException.h
Hi.
This patch fixes failure messages from ```bandit::Matchers``` by make ```MatchersException``` inherit ```assertion_exception```.
For example, without this patch, the failure message from this code 
``` c++
#include <bandit/bandit.h>
using namespace bandit;
using namespace bandit::Matchers;
go_bandit([]() {
describe("1 and 2", []() {
it("should be equal", []() { 1 must equal(2); });
});
});
```
goes like
```
1 and 2 should be equal:
exception: std::exception
```
and with this patch, it goes like
```
1 and 2 should be equal:
foo.cc:26: Expected <1> to equal <2>
```
=> Fix failure messages from MatcherException.

bandit/assertion_frameworks/matchers/BeFalsy.h, bandit/assertion_frameworks/matchers/BeTruthy.h
This patch suprress the warning from gcc-5+ and clang-3.6+ about implicit conversion from ```nullptr_t``` to ```bool```.
=> Avoid implicit conversion from nullptr_t to bool.

bandit/assertion_frameworks/matchers/Contain.h
std::vector doesn’t work without #include \<vector\>
=> Fixed a missing STL include in Contain.h

bandit/reporters/colorizer.h
Check for (not) defined NOMINMAX rather than MINGW32
Adresses https://github.com/joakimkarlsson/bandit/issues/19
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/joakimkarlsson/bandit/55)
=> fix(windows): prevent redefinition of NOMINMAX

bandit/assertion_frameworks/matchers/BeFalsy.h, bandit/assertion_frameworks/matchers/BeTruthy.h, bandit/reporters/colorizer.h
Checked with GCC 5.1.0 under Windows
=> Fix unused-parameter and missing-field-initializers warnings

bandit/reporters/reporters.h, bandit/run_policies/run_policy.h, bandit/runner.h
Hi guys,
I am currently looking for different unit test tools and bandit seems a very interesting choice!
However, when running clang-tidy on a minimal project, I get some warnings and I do not want any warning (as I set an option so that they automatically trigger errors)...
These warnings are related to the registration and access to registered values contained in a single function for run_policy and listener (it is a bit tricky to initialise static variables in header files...). The two commits of this pull request fix these warnings and, in my opinion, improve a bit the design as the registration and the access to the variables are now in two different functions and enable to test if they have been registered before being retrieved (but there is more code because of the initialisation …
=> Separating registration of from access to registered values

CMakeLists.txt, bandit/assertion_frameworks/matchers/must.h, specs/matchers/equal.cpp, specs/matchers/throw_exception.cpp
These compatibility changes make bandit work with old versions
of Visual Studio (and gcc) such that appveyor is successful.
=> Make appveyor work again

bandit/reporters/info_reporter.h, specs/reporters/info_reporter.spec.cpp
The info reporter in the original version contains various bugs (for example,
skipping can lead to crashes) and the reporter is not as fancy as it could be.
For example, the new info reporter gives summaries for each context
and omits showing nested contexts if they are skipped.
(Note that we are using this version of the info reporter for over two years now,
so I only cherry-picked the development commits.)
[WIP] because I am currently writing the long awaited tests for the reporter and this will lead
to some further behavior-changing commits. I only started the pull request
to allow a review of the non-WIP commits. (I am used to GitLab where [WIP]
makes the pull request unmergeable. I hope this works here, too.)
=> Fix and enhance info reporter

.gitmodules, bandit/bandit.h
Matchers is currently unused in this repository, hence the
submodule and the inclusion of matchers.h is removed.
This is a compatibility-breaking change.
Users who want to use bandit with matchers now have to do
add something like
```c++
#include <path_to_matchers/matchers/matchers.h>
using namespace Matchers;
```
to their sources.
=> Remove matchers submodule

bandit/reporters/colored_reporter.h, bandit/reporters/colorizer.h, bandit/reporters/dots_reporter.h, bandit/reporters/info_reporter.h, bandit/reporters/single_line_reporter.h, bandit/reporters/spec_reporter.h, specs/reporters/dots_reporter.spec.cpp, specs/reporters/info_reporter.spec.cpp, specs/reporters/single_line_reporter.spec.cpp, specs/reporters/xunit_reporter.spec.cpp
The colorizer for Windows is changed that it
* does not change the background color and
* has intense colors
Additionally, reporters with colors now always reset
the colorizer on destruction (regardless of the operating
system).
This is related to #90.
=> Change colorizer for Windows

CMakeLists.txt, bandit/grammar.h, bandit/options.h, bandit/runner.h, specs/before_each_after_each.spec.cpp, specs/describe.spec.cpp, specs/fakes/fake_context.h, specs/fakes/fake_reporter.h, specs/fakes/fakes.h, specs/fakes/logging_fake.h, specs/it.spec.cpp, specs/options.spec.cpp, specs/run.spec.cpp, specs/specs.h, specs/util/argv_helper.h, specs/util/util.h
The main change for the user is that options are
checked now. By default, option usage errors do not
lead to failed return values, but you can add a `false`
to your `bandit::run` call to enable that.
The main internal change is that the code behind
choice-based options like `--formatter` and `--reporter`
are unified.
The options spec is extended to reflect those changes.
=> Improve option handling

bandit/options.h
This prevents compiling cleanly with -Wpedantic and warning as errors.
=> Fix extra semicolon warning message.

bandit/reporters/info_reporter.h, bandit/reporters/progress_reporter.h, specs/reporters/dots_reporter.spec.cpp, specs/reporters/single_line_reporter.spec.cpp
This reverts e271234b4deedbda4e0a23dafd34b2a950d066d6 semantically.
Issue #10 is not considered as a bug but as a feature.
When the user intends to skip all tests for some reason, it should
not be considered being a failure.
This is a compatibility-breaking change.
=> Report successful run even if no specs found

bandit/options.h, bandit/reporters/crash_reporter.h, bandit/reporters/reporters.h, bandit/runner.h, specs/reporters/crash_reporter.spec.cpp
The crash reporter is a reporter that is suited for test suites
that can crash (segmentation fault and alike) and when multiple
bandit invokations are run in parallel.
When a test item is started, the crash reporter prints the
whole context (separated by " | ") and the item on one line.
The test summary only contains failures and is prefixed by
'#' so that you can grep for it. For example, using the default
failure formatter,
```sh
run_tests --reporter=crash >log 2>&1 ||
grep -B 1 -A 4 "^#" log ||
tail -n 10 log
```
gives a nice output of the failure summary (if there are failures)
or outputs the last 10 lines of the output (if it crashes)
or is just silent otherwise.
Resolves #83 where such a reporter has been requested.
=> Add crash reporter

bandit/filter_chain.h, bandit/options.h, bandit/run_policies/bandit_run_policy.h, bandit/runner.h, specs/options.spec.cpp, specs/run_policies/bandit_run_policy.spec.cpp
A filter chain is now used by run policies instead of
skip/only patterns.
This allows a more intuitive usage of (multiple) --skip
and --only options.
However, this comes with a compatibility-breaking change:
Up to this commit, context skips were ignored if there are
matching "only"s. This behavior is now changed. --skip
and --only apply a filter (the one or the other way),
no matter in what "stage" they match.
This resolves #88.
=> Replace skip/only patterns by filter chain

bandit/assertion_exception.h, bandit/reporters/crash_reporter.h, bandit/reporters/info_reporter.h
This fixes warnings associated with 1) missing overrides, 2) not including #string in assertion_exception.h, 3) shadowing of contexts_.
=> Fix clang warnings

CMakeLists.txt, bandit/colorizers.h, bandit/colorizers/backend.h, bandit/colorizers/colorizer.h, bandit/colorizers/dark.h, bandit/colorizers/interface.h, bandit/colorizers/light.h, bandit/colorizers/off.h, bandit/options.h, bandit/reporters/colored_base.h, bandit/reporters/dots.h, bandit/reporters/info.h, bandit/reporters/singleline.h, bandit/reporters/spec.h, bandit/reporters/summary.h, bandit/runner.h, docs/releases.md, docs/runningtests.md, specs/colorizer.cpp, specs/options.cpp, specs/reporters/dots.cpp, specs/reporters/info.cpp, specs/reporters/singleline.cpp
This merge request introduces a colorizer interface, replaces the
default coloring by the `light` colorizer and the disabled colors (using
the `--no-color` option that is now removed) by the `off` colorizer,
and finally adds a `dark` colorizer for light backgrounds.
This should fix #90, at least to some extent.
=> Introduce choosable colorizers

specs/reporters/dots.cpp, specs/reporters/info.cpp, specs/reporters/spec.cpp, specs/run.cpp, specs/util/argv_helper.h
As codecov shows, the spec reporter was not tested at all. It is now.
While at it, a few other minors/typos are fixed.
=> Test spec reporter

bandit/adapters.h, bandit/adapters/interface.h, bandit/colorizers/interface.h, bandit/context.h, bandit/controller.h, bandit/failure_formatters.h, bandit/failure_formatters/interface.h, bandit/grammar.h, bandit/options.h, bandit/reporters.h, bandit/reporters/colored_base.h, bandit/reporters/interface.h, bandit/reporters/summary.h, bandit/run_policies.h, bandit/run_policies/interface.h, bandit/runner.h, bandit/settings.h, docs/releases.md, specs/before_each_after_each.cpp, specs/describe.cpp, specs/fakes/fake_reporter.h, specs/it.cpp, specs/options.cpp, specs/run.cpp
This is an attempt to make the internals of bandit more flexible.
The purpose of `controller_t` is to contain all the important things, like
assertion framework, colorizer, failure formatter, reporter, run policy,
and what else may come in the future. Now all our grammar is based
on this type (and the static/inline grammar functions now call the according
`controller_t` methods, hence the name).
The introduction of `controller_t` also allows to make the addition of
colorizers/formatters/reporters more flexible: simply define it and
then add it with a lambda that changes the corresponding settings.
This allows to get rid of all the code about colorizers/formatters/reporters
in different places of the bandit source and hence error-prone, and
it now allows that users may define their own …
=> Introduce controller_t and rework options

bandit/registration/registrar.h
Unity builds (as provided by cotire's "all_unity" target) save
about 50% of the compilation/linking time and allow better
optimization.
=> Allow multiple go_bandit()s and thus unity builds

bandit/adapters/interface.h, bandit/colorizers/interface.h, bandit/context.h, bandit/failure_formatters/interface.h, bandit/reporters/interface.h, bandit/run_policies/interface.h, specs/before_each_after_each.cpp, specs/context.cpp, specs/describe.cpp, specs/it.cpp, specs/reporters/crash.cpp, specs/reporters/dots.cpp, specs/reporters/info.cpp, specs/reporters/singleline.cpp, specs/reporters/spec.cpp, specs/reporters/xunit.cpp, specs/run_policies/bandit.cpp
In some interfaces, the declaration of virtual destructors has been forgotten.
They are now added which revealed another bug in some specs
where the colorizer can be destructed before the reporter using that colorizer
is destructed.
This bug is also fixed.
This PR also fixes a readability issue with `std::unique_ptr` assignments.
=> Use virtual destructors in interfaces

bandit/external/optionparser.h
Your code was triggering `old-style-cast` warning. Would you accept this fix?
=> Fix old style cast warnings

bandit/failure_formatters.h, bandit/failure_formatters/posix.h, bandit/failure_formatters/qt_creator.h, bandit/runner.h, docs/runningtests.md, specs/failure_formatters/qt_creator.cpp, specs/options.cpp
Adding the `file://` prefix before a file name allows to enable hyperlink on the Qt Creator output log which make very convenient to find failing test.
What do you think of this feature? Would it be annoying for people not using Qt Creator?
=> Make Qt Creator formatter (POSIX formatter with file://)

bandit/external/optionparser.h, bandit/options.h
This PR simply replace 0 or NULL by nullptr. It allow compiling the code with the following compiler flags:
```
-Werror -Wzero-as-null-pointer-constant
```
I updated the snowhouse version but I guess https://github.com/banditcpp/snowhouse/pull/41 should be merged first.
=> Fix zero-as-null-pointer-constant warning

CMakeLists.txt
sakra/cotire#81
Without [this policy](https://cmake.org/cmake/help/v3.13/policy/CMP0058.html), the following warning is raised:
```shellsession
$ cmake -GNinja -Bbuild -S.
…
-- cotire 1.8.0 loaded.
-- CXX target bandit-specs cotired.
-- Configuring done
-- Generating done
CMake Warning (dev):
Policy CMP0058 is not set: Ninja requires custom command byproducts to be
explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
This project specifies custom command DEPENDS on files in the build tree
that are not specified as the OUTPUT or BYPRODUCTS of any
add_custom_command or add_custom_target:
bandit-specs_CXX_cotire.cmake
For compatibility with versions of CMake that did not have the BYPRODUCTS
option, CMake …
```
=> Set policy CMP0058
